name = "bible-study-tutor"
pages_build_output_dir = "dist"
compatibility_date = "2026-07-24"

[vars]
EXPO_PUBLIC_SITE_URL = "https://biblestudytutor.org"
SITE_URL = "https://biblestudytutor.org"
EXPO_PUBLIC_CONVEX_URL = "https://fabulous-ladybug-435.convex.cloud"
EXPO_PUBLIC_CONVEX_SITE_URL = "https://fabulous-ladybug-435.convex.site"
