import { View } from "react-native";

import { Card } from "@/components/ui";
import { BibleReaderControls } from "@/components/BibleReaderControls";
import { BibleReaderNavigator } from "@/components/BibleReaderNavigator";
import { BibleReaderPassage } from "@/components/BibleReaderPassage";
import { BibleSearchPanel } from "@/components/BibleSearchPanel";

export function BibleTab({
  styles,
  compactLayout,
  phoneLayout,
  bibleDarkMode,
  readerNavCollapsed,
  translations,
  bibleTranslation,
  readBibleChapterCount,
  readBibleChapters,
  currentBookReadChapterCount,
  bibleBookmarks,
  bibleReaderHistory,
  readerHistoryCollapsed,
  bookmarksCollapsed,
  bookmarksExpanded,
  bookmarkNotesOnly,
  bookmarkSearch,
  readerBookSearch,
  visibleBibleBookmarks,
  filteredBibleBookmarks,
  activeBookmarkNoteId,
  bookmarkNoteDraft,
  readerMobileMenu,
  expandedMobileReaderBook,
  readerBook,
  readerChapter,
  readerBookSections,
  readerMatchesActiveBibleReadingPlanDay,
  activeBibleReadingPlan,
  activeBibleReadingPlanToday,
  activeBibleReadingPlanTodayLabel,
  activeBibleReadingPlanCompletedCount,
  activeBibleReadingPlanComplete,
  activeBibleReadingPlanOpen,
  biblePlanStatus,
  otherActiveBibleReadingPlans,
  onOpenPlansTab,
  onOpenActivePlanReading,
  onOpenFollowedPlanReading,
  onToggleReaderNavCollapsed,
  onSelectTranslation,
  onBookSearchChange,
  onToggleHistoryCollapsed,
  onClearHistory,
  onOpenHistoryItem,
  onToggleBookmarksCollapsed,
  onBookmarkSearchChange,
  onToggleBookmarkNotesOnly,
  onOpenBookmark,
  onOpenBookmarkNote,
  onRemoveBookmark,
  onBookmarkNoteDraftChange,
  onSaveBookmarkNote,
  onDeleteBookmarkNote,
  onCancelBookmarkNote,
  onToggleBookmarksExpanded,
  onToggleMobileMenu,
  onSelectMobileBook,
  onSelectBook,
  onSelectChapter,
  onClearReadBook,
  bibleSearchCollapsed,
  bibleSearchQuery,
  bibleSearchScope,
  bibleSearchMode,
  bibleSearchBook,
  bibleSearchBookOptions,
  bibleSearchBookMenuOpen,
  bibleSearchCriteriaOpen,
  bibleSearchTranslation,
  bibleSearchStatus,
  bibleSearchDuration,
  bibleSearchActiveQuery,
  bibleSearchSections,
  onToggleBibleSearchCollapsed,
  onBibleSearchQueryChange,
  onRunBibleSearch,
  onClearBibleSearch,
  onToggleBibleSearchCriteria,
  onSelectBibleSearchScope,
  onSelectBibleSearchMode,
  onToggleBibleSearchBookMenu,
  onSelectBibleSearchBook,
  onBibleSearchSummaryLayout,
  renderBibleSearchResultActions,
  readerStudyReference,
  readerChapterDraft,
  readerChapterCount,
  selectedReaderVerses,
  currentChapterRead,
  currentChapterBookmarked,
  readerIconTooltip,
  onStudyReaderChapter,
  onClearReaderSelection,
  onMoveReaderChapter,
  onChapterDraftChange,
  onCommitChapter,
  onToggleChapterRead,
  onBookmarkChapter,
  onClearReadingProgress,
  readerIconHoverProps,
  hideReaderTooltip,
  readerPassage,
  readerStatus,
  readerMemoryStatus,
  activeReaderActionVerse,
  readerMemoryVerseKeys,
  activeReadingPlanDay,
  activeReadingPlanDayCompleted,
  planReadingMode,
  planReadingCanMovePrevious,
  planReadingCanMoveNext,
  planReadingChunkLabel,
  planReadingNote,
  planReadingFullChapter,
  onMarkActiveReadingPlanDayComplete,
  onExitPlanReading,
  currentSelectionBookmarked,
  currentSelectionBookmark,
  selectedReaderVersesAlreadyInMemory,
  onPassageLayout,
  onVerseLayout,
  onToggleVerse,
  onBookmarkSelection,
  onOpenNote,
  onPrintWorksheet,
  onSaveMemory,
  isVerseBookmarked,
  isVerseNoted
}: any) {
  const displayedReaderReference = planReadingMode && readerPassage?.reference ? readerPassage.reference : readerStudyReference;

  return (
    <View style={[styles.bibleReaderLayout, compactLayout && styles.stackedLayout, bibleDarkMode && styles.accountDarkLayout]}>
      <BibleReaderNavigator
        styles={styles}
        darkMode={bibleDarkMode}
        phoneLayout={phoneLayout}
        compactLayout={compactLayout}
        collapsed={readerNavCollapsed}
        translations={translations}
        translationId={bibleTranslation}
        readChapterCount={readBibleChapterCount}
        readChapters={readBibleChapters}
        bookmarks={bibleBookmarks}
        history={bibleReaderHistory}
        historyCollapsed={readerHistoryCollapsed}
        bookmarksCollapsed={bookmarksCollapsed}
        bookmarksExpanded={bookmarksExpanded}
        bookmarkNotesOnly={bookmarkNotesOnly}
        bookmarkSearch={bookmarkSearch}
        bookSearch={readerBookSearch}
        visibleBookmarks={visibleBibleBookmarks}
        filteredBookmarksCount={filteredBibleBookmarks.length}
        activeBookmarkNoteId={activeBookmarkNoteId}
        bookmarkNoteDraft={bookmarkNoteDraft}
        mobileMenu={readerMobileMenu}
        expandedBook={expandedMobileReaderBook}
        readerBook={readerBook}
        readerChapter={readerChapter}
        readerBookSections={readerBookSections}
        activeBibleReadingPlan={activeBibleReadingPlan}
        activeBibleReadingPlanToday={activeBibleReadingPlanToday}
        activeBibleReadingPlanTodayLabel={activeBibleReadingPlanTodayLabel}
        activeBibleReadingPlanCompletedCount={activeBibleReadingPlanCompletedCount}
        activeBibleReadingPlanComplete={activeBibleReadingPlanComplete}
        activeBibleReadingPlanOpen={activeBibleReadingPlanOpen}
        biblePlanStatus={biblePlanStatus}
        otherActiveBibleReadingPlans={otherActiveBibleReadingPlans}
        onOpenPlansTab={onOpenPlansTab}
        onOpenActivePlanReading={onOpenActivePlanReading}
        onOpenFollowedPlanReading={onOpenFollowedPlanReading}
        onToggleCollapsed={onToggleReaderNavCollapsed}
        onSelectTranslation={onSelectTranslation}
        onBookSearchChange={onBookSearchChange}
        onToggleHistoryCollapsed={onToggleHistoryCollapsed}
        onClearHistory={onClearHistory}
        onOpenHistoryItem={onOpenHistoryItem}
        onToggleBookmarksCollapsed={onToggleBookmarksCollapsed}
        onBookmarkSearchChange={onBookmarkSearchChange}
        onToggleBookmarkNotesOnly={onToggleBookmarkNotesOnly}
        onOpenBookmark={onOpenBookmark}
        onOpenBookmarkNote={onOpenBookmarkNote}
        onRemoveBookmark={onRemoveBookmark}
        onBookmarkNoteDraftChange={onBookmarkNoteDraftChange}
        onSaveBookmarkNote={onSaveBookmarkNote}
        onDeleteBookmarkNote={onDeleteBookmarkNote}
        onCancelBookmarkNote={onCancelBookmarkNote}
        onToggleBookmarksExpanded={onToggleBookmarksExpanded}
        onToggleMobileMenu={onToggleMobileMenu}
        onSelectMobileBook={onSelectMobileBook}
        onSelectChapter={onSelectChapter}
        onClearReadBook={onClearReadBook}
      />

      <Card style={[styles.bibleReaderContentCard, compactLayout && styles.fluidCard, bibleDarkMode && styles.accountDarkMainCard]}>
        <BibleSearchPanel
          styles={styles}
          darkMode={bibleDarkMode}
          phoneLayout={phoneLayout}
          collapsed={bibleSearchCollapsed}
          query={bibleSearchQuery}
          scope={bibleSearchScope}
          mode={bibleSearchMode}
          book={bibleSearchBook}
          bookOptions={bibleSearchBookOptions}
          bookMenuOpen={bibleSearchBookMenuOpen}
          criteriaOpen={bibleSearchCriteriaOpen}
          translationLabel={bibleSearchTranslation}
          translationId={bibleTranslation}
          status={bibleSearchStatus}
          duration={bibleSearchDuration}
          activeQuery={bibleSearchActiveQuery}
          sections={bibleSearchSections}
          onToggleCollapsed={onToggleBibleSearchCollapsed}
          onQueryChange={onBibleSearchQueryChange}
          onRunSearch={onRunBibleSearch}
          onClearSearch={onClearBibleSearch}
          onToggleCriteria={onToggleBibleSearchCriteria}
          onSelectScope={onSelectBibleSearchScope}
          onSelectMode={onSelectBibleSearchMode}
          onToggleBookMenu={onToggleBibleSearchBookMenu}
          onSelectBook={onSelectBibleSearchBook}
          onSummaryLayout={onBibleSearchSummaryLayout}
          renderResultActions={renderBibleSearchResultActions}
        />

        <BibleReaderControls
          styles={styles}
          darkMode={bibleDarkMode}
          phoneLayout={phoneLayout}
          translationId={bibleTranslation}
          readerReference={displayedReaderReference}
          planReadingMode={planReadingMode}
          chapterDraft={readerChapterDraft}
          chapterCount={readerChapterCount}
          selectedVerseCount={selectedReaderVerses.length}
          currentChapterRead={currentChapterRead}
          currentChapterBookmarked={currentChapterBookmarked}
          readChapterCount={readBibleChapterCount}
          currentBookReadChapterCount={currentBookReadChapterCount}
          tooltip={readerIconTooltip}
          onStudy={onStudyReaderChapter}
          onClearSelection={onClearReaderSelection}
          onMoveChapter={onMoveReaderChapter}
          onChapterDraftChange={onChapterDraftChange}
          onCommitChapter={onCommitChapter}
          onToggleChapterRead={onToggleChapterRead}
          onBookmarkChapter={onBookmarkChapter}
          onClearReadingProgress={onClearReadingProgress}
          readerIconHoverProps={readerIconHoverProps}
          hideReaderTooltip={hideReaderTooltip}
        />
        <BibleReaderPassage
          styles={styles}
          darkMode={bibleDarkMode}
          phoneLayout={phoneLayout}
          passage={readerPassage}
          status={readerStatus}
          memoryStatus={readerMemoryStatus}
          selectedVerses={selectedReaderVerses}
          activeActionVerse={activeReaderActionVerse}
          readerReference={readerStudyReference}
          memoryVerseKeys={readerMemoryVerseKeys}
          matchesActiveReadingPlanDay={readerMatchesActiveBibleReadingPlanDay}
          activeReadingPlanDay={activeReadingPlanDay}
          activeReadingPlanDayCompleted={activeReadingPlanDayCompleted}
          planReadingMode={planReadingMode}
              planReadingCanMovePrevious={planReadingCanMovePrevious}
              planReadingCanMoveNext={planReadingCanMoveNext}
              planReadingChunkLabel={planReadingChunkLabel}
              planReadingNote={planReadingNote}
              planReadingFullChapter={planReadingFullChapter}
          currentSelectionBookmarked={currentSelectionBookmarked}
          currentSelectionBookmark={currentSelectionBookmark}
          selectedVersesAlreadyInMemory={selectedReaderVersesAlreadyInMemory}
          currentChapterRead={currentChapterRead}
          onPassageLayout={onPassageLayout}
          onVerseLayout={onVerseLayout}
          onToggleVerse={onToggleVerse}
          onOpenStudy={onStudyReaderChapter}
          onBookmarkSelection={onBookmarkSelection}
          onOpenNote={onOpenNote}
          onPrintWorksheet={onPrintWorksheet}
          onSaveMemory={onSaveMemory}
          onClearSelection={onClearReaderSelection}
          onMoveChapter={onMoveReaderChapter}
          onToggleChapterRead={onToggleChapterRead}
          onMarkActiveReadingPlanDayComplete={onMarkActiveReadingPlanDayComplete}
          onExitPlanReading={onExitPlanReading}
          isVerseBookmarked={isVerseBookmarked}
          isVerseNoted={isVerseNoted}
        />
      </Card>
    </View>
  );
}
